/*
 * Paperless Rest Server
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using PaperlessRestService.Attributes;

using Microsoft.AspNetCore.Authorization;
using PaperlessRestService.Models;

namespace PaperlessRestService.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class TasksApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/api/acknowledge_tasks")]
        [ValidateModelState]
        [SwaggerOperation("AckTasks")]
        [SwaggerResponse(statusCode: 200, type: typeof(InlineResponse20020), description: "Success")]
        public virtual IActionResult AckTasks([FromBody]ApiAcknowledgeTasksBody body)
        {
            return Ok();
        }2<2.

        /// <summary>
        /// 
        /// </summary>
        /// <response code="200">Success</response>
        [HttpGet]
        [Route("/api/tasks")]
        [ValidateModelState]
        [SwaggerOperation("GetTasks")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<InlineResponse20019>), description: "Success")]
        public virtual IActionResult GetTasks()
        {
            Random rand = new Random();

            return Ok(new List<Task> { new Task { 
                Type = TaskType.file, 
                DateCreated = DateTime.Now.AddDays(rand.Next(-10, 0)), 
                DateDone = DateTime.Now.AddDays(rand.Next(-10, 0)) 
            } });
        }
    }
}
