name: "paperless-api"
version: "3.8"  

volumes:
  paperless-api:
  rabbitmq:
  postgres-db:

networks:
  internal-nw:
     internal: true 
  external-nw:
     internal: false
  
services:
  paperless-rest:
    #image: if22b190/paperless:latest #ergänzung sobald dieser Container von github gebuildet und gepushed wird, könnt ihr den damit holen
    build: REST_API/
    container_name: paperless-rest
    volumes:
      - paperless-api:/var/paperless-rest
    ports:
      - "8000:80"
    networks: 
      - external-nw

  paperless-ui:
    build: PaperlessUI/
    container_name: paperless-ui
    volumes:
      - paperless-api:/var/www
    ports:
      - "80:4200"
    networks: 
      - external-nw

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
      - rabbitmq:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASSWORD=admin
    ports:
      - "5672:5672"
      - "15672:15672"
    networks: 
      - internal-nw

  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=paperless
    volumes:
      - postgres-db:/var/lib/postgresql/data
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql # ergänzung sobald wie eine sql.init file haben
    ports:
      - "5432:5432"
    networks: 
      - internal-nw