name: Services-Dev-Pipeline

on:
  push:
    branches: [ "Development" ]
  pull_request:
    branches: [ "Development" ]

jobs:

  REST-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      working-directory: REST_API/PaperlessRestService.ServiceAgents
      run: docker build . -t if22b190/paperless-services:dev

    - name: Log in into DockerHub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push the images to Docker Hub
      run: docker push if22b190/paperless-services:dev