name: Docker Image CI with dotnet

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: restore dependencies
      run: dotnet restore
      
    - name: build dotnet
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Log in into DockerHub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: extract metadata (tags, labels) for docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: if22b190/paperless
    
    - name: Build the Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./PaperlessRestService/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
