name: Docker Image CI with dotnet

on:
  push:
    branches: [ "master" , "development"]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log in into DockerHub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: extract metadata (tags, labels) for docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: if22b190/paperless
    
    - name: Build the Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./PaperlessRestService/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
